# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef24d84255ebbbcd65f88d9b7c8331b804e1012201da3cb2938a00e23a68f68779c0fe4adc55e2517fc90a522f970bba56f1903cb3cc64a5618efa01e12df709

test:
  secret_key_base: 5a92b8cf24f60de8015ef08a671550c4df3f7236e430002468c05e713e1b7e2234ba156e31554478b11ac0dfc393fe8e0364053b46df6651b2a9ccac1beea2e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
